defaults:
  actions:
    backport:
      # By default, all backport PRs are assigned to the original author.
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: backport patches to v5.0.x branch
    conditions:
      - base=main
      - label=backport/v5.0.x
    actions:
      backport:
        branches:
          - v5.0.x
