defaults:
  actions:
    backport:
      # By default, all backport PRs are assigned to the original author.
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: backport patches to v4.0.x branch
    conditions:
      - base=main
      - label=backport/v4.0.x
    actions:
      backport:
        branches:
          - release/v4.0.x
  - name: backport patches to v4.1.x branch
    conditions:
      - base=main
      - label=backport/v4.1.x
    actions:
      backport:
        branches:
          - release/v4.1.x
