modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: Noble
      pre_blockers: [ upgrade ]
      begin_blockers: [ capability, distribution, slashing, evidence, staking, ibc, authz ]
      end_blockers: [ crisis, staking, feegrant, group, forwarding ]
      init_genesis: [ capability, transfer, auth, bank, staking, distribution, slashing, crisis, fiat-tokenfactory, genutil, ibc, interchainaccounts, packetfowardmiddleware, evidence, authz, feegrant, upgrade, vesting, cctp, authority, forwarding, circuit, group ]
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
        - module_name: fiat-tokenfactory
          kv_store_key: fiattokenfactory
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: noble
      module_account_permissions:
        - account: fee_collector
        - account: distribution
        - account: interchainaccounts
        - account: bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: not_bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: transfer
          permissions: [ burner, minter ]
        - account: fiat-tokenfactory
          permissions: [ burner, minter ]
        - account: upgrade
          permissions: [ burner ]
      authority: authority # Utilize our custom x/authority module.
  - name: vesting
    config:
      "@type": cosmos.vesting.module.v1.Module
  - name: authz
    config:
      "@type": cosmos.authz.module.v1.Module
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
      blocked_module_accounts_override:
        [ auth, distribution, bonded_tokens_pool, not_bonded_tokens_pool ]
      authority: authority # Utilize our custom x/authority module.
      # NOTE: We do not need to set a custom restriction ordering as FiatTokenFactory and Forwarding are already ordered correctly by default.
  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  - name: crisis
    config:
      "@type": cosmos.crisis.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  - name: distribution
    config:
      "@type": cosmos.distribution.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  - name: evidence
    config:
      "@type": cosmos.evidence.module.v1.Module
  - name: feegrant
    config:
      "@type": cosmos.feegrant.module.v1.Module
  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module
  - name: group
    config:
      "@type": cosmos.group.module.v1.Module
  - name: params
    config:
      "@type": cosmos.params.module.v1.Module
  - name: slashing
    config:
      "@type": cosmos.slashing.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config
  - name: upgrade
    config:
      "@type": cosmos.upgrade.module.v1.Module
      authority: authority # Utilize our custom x/authority module.

  - name: fiat-tokenfactory
    config:
      "@type": circle.fiattokenfactory.module.v1.Module
  - name: cctp
    config:
      "@type": circle.cctp.module.v1.Module

  - name: authority
    config:
      "@type": noble.authority.module.v1.Module
  - name: forwarding
    config:
      "@type": noble.forwarding.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  # TODO(@john): TokenFactory
