// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: circle/cctp/v1/burn_message.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BurnMessage struct {
	Version       uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	BurnToken     []byte `protobuf:"bytes,2,opt,name=burn_token,json=burnToken,proto3" json:"burn_token,omitempty"`
	MintRecipient []byte `protobuf:"bytes,3,opt,name=mint_recipient,json=mintRecipient,proto3" json:"mint_recipient,omitempty"`
	Amount        uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	MessageSender []byte `protobuf:"bytes,5,opt,name=message_sender,json=messageSender,proto3" json:"message_sender,omitempty"`
}

func (m *BurnMessage) Reset()         { *m = BurnMessage{} }
func (m *BurnMessage) String() string { return proto.CompactTextString(m) }
func (*BurnMessage) ProtoMessage()    {}
func (*BurnMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_770538a2f8e64d6c, []int{0}
}
func (m *BurnMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BurnMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BurnMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BurnMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurnMessage.Merge(m, src)
}
func (m *BurnMessage) XXX_Size() int {
	return m.Size()
}
func (m *BurnMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BurnMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BurnMessage proto.InternalMessageInfo

func (m *BurnMessage) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BurnMessage) GetBurnToken() []byte {
	if m != nil {
		return m.BurnToken
	}
	return nil
}

func (m *BurnMessage) GetMintRecipient() []byte {
	if m != nil {
		return m.MintRecipient
	}
	return nil
}

func (m *BurnMessage) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BurnMessage) GetMessageSender() []byte {
	if m != nil {
		return m.MessageSender
	}
	return nil
}

func init() {
	proto.RegisterType((*BurnMessage)(nil), "circle.cctp.v1.BurnMessage")
}

func init() { proto.RegisterFile("circle/cctp/v1/burn_message.proto", fileDescriptor_770538a2f8e64d6c) }

var fileDescriptor_770538a2f8e64d6c = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x63, 0x28, 0x45, 0x18, 0xda, 0xc1, 0x03, 0xf2, 0x82, 0x15, 0x90, 0x90, 0x32, 0x40,
	0xac, 0x8a, 0x1b, 0x74, 0x60, 0x63, 0x09, 0x4c, 0x2c, 0x51, 0x63, 0x1e, 0xc5, 0xa2, 0x79, 0x8e,
	0x6c, 0x27, 0x82, 0x5b, 0x70, 0x10, 0x0e, 0xc2, 0xd8, 0x91, 0x11, 0x25, 0x17, 0x41, 0xb1, 0xdb,
	0xf1, 0xff, 0xf4, 0xfd, 0x96, 0xdf, 0x4f, 0x2f, 0x95, 0xb6, 0x6a, 0x03, 0x52, 0x29, 0xdf, 0xc8,
	0x6e, 0x21, 0xab, 0xd6, 0x62, 0x59, 0x83, 0x73, 0xab, 0x35, 0xe4, 0x8d, 0x35, 0xde, 0xb0, 0x79,
	0x54, 0xf2, 0x51, 0xc9, 0xbb, 0xc5, 0xd5, 0x37, 0xa1, 0xa7, 0xcb, 0xd6, 0xe2, 0x43, 0xb4, 0x18,
	0xa7, 0xc7, 0x1d, 0x58, 0xa7, 0x0d, 0x72, 0x92, 0x92, 0x6c, 0x56, 0xec, 0x23, 0xbb, 0xa0, 0x34,
	0xbc, 0xe7, 0xcd, 0x3b, 0x20, 0x3f, 0x48, 0x49, 0x76, 0x56, 0x9c, 0x8c, 0xe4, 0x69, 0x04, 0xec,
	0x9a, 0xce, 0x6b, 0x8d, 0xbe, 0xb4, 0xa0, 0x74, 0xa3, 0x01, 0x3d, 0x3f, 0x0c, 0xca, 0x6c, 0xa4,
	0xc5, 0x1e, 0xb2, 0x73, 0x3a, 0x5d, 0xd5, 0xa6, 0x45, 0xcf, 0x27, 0x29, 0xc9, 0x26, 0xc5, 0x2e,
	0x85, 0x7a, 0xfc, 0x42, 0xe9, 0x00, 0x5f, 0xc0, 0xf2, 0xa3, 0x5d, 0x3d, 0xd2, 0xc7, 0x00, 0x97,
	0xf7, 0x3f, 0xbd, 0x20, 0xdb, 0x5e, 0x90, 0xbf, 0x5e, 0x90, 0xaf, 0x41, 0x24, 0xdb, 0x41, 0x24,
	0xbf, 0x83, 0x48, 0x9e, 0x6f, 0xd6, 0xda, 0xbf, 0xb5, 0x55, 0xae, 0x4c, 0x2d, 0xe3, 0x8d, 0xaf,
	0x1a, 0x25, 0x9a, 0x6a, 0x03, 0xb7, 0x61, 0x8f, 0x8f, 0x38, 0x8b, 0xff, 0x6c, 0xc0, 0x55, 0xd3,
	0xb0, 0xc6, 0xdd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xf3, 0xf4, 0x18, 0x32, 0x01, 0x00,
	0x00,
}

func (m *BurnMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BurnMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BurnMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageSender) > 0 {
		i -= len(m.MessageSender)
		copy(dAtA[i:], m.MessageSender)
		i = encodeVarintBurnMessage(dAtA, i, uint64(len(m.MessageSender)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Amount != 0 {
		i = encodeVarintBurnMessage(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MintRecipient) > 0 {
		i -= len(m.MintRecipient)
		copy(dAtA[i:], m.MintRecipient)
		i = encodeVarintBurnMessage(dAtA, i, uint64(len(m.MintRecipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BurnToken) > 0 {
		i -= len(m.BurnToken)
		copy(dAtA[i:], m.BurnToken)
		i = encodeVarintBurnMessage(dAtA, i, uint64(len(m.BurnToken)))
		i--
		dAtA[i] = 0x12
	}
	if m.Version != 0 {
		i = encodeVarintBurnMessage(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBurnMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovBurnMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BurnMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovBurnMessage(uint64(m.Version))
	}
	l = len(m.BurnToken)
	if l > 0 {
		n += 1 + l + sovBurnMessage(uint64(l))
	}
	l = len(m.MintRecipient)
	if l > 0 {
		n += 1 + l + sovBurnMessage(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovBurnMessage(uint64(m.Amount))
	}
	l = len(m.MessageSender)
	if l > 0 {
		n += 1 + l + sovBurnMessage(uint64(l))
	}
	return n
}

func sovBurnMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBurnMessage(x uint64) (n int) {
	return sovBurnMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BurnMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBurnMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BurnMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BurnMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurnMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnToken", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurnMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBurnMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBurnMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurnToken = append(m.BurnToken[:0], dAtA[iNdEx:postIndex]...)
			if m.BurnToken == nil {
				m.BurnToken = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRecipient", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurnMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBurnMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBurnMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintRecipient = append(m.MintRecipient[:0], dAtA[iNdEx:postIndex]...)
			if m.MintRecipient == nil {
				m.MintRecipient = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurnMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageSender", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBurnMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBurnMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBurnMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageSender = append(m.MessageSender[:0], dAtA[iNdEx:postIndex]...)
			if m.MessageSender == nil {
				m.MessageSender = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBurnMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBurnMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBurnMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBurnMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBurnMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBurnMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBurnMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBurnMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBurnMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBurnMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBurnMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBurnMessage = fmt.Errorf("proto: unexpected end of group")
)
