// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cctp/denoms.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Denoms struct {
	Address   string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Allowance types.Coin `protobuf:"bytes,2,opt,name=allowance,proto3" json:"allowance"`
}

func (m *Denoms) Reset()         { *m = Denoms{} }
func (m *Denoms) String() string { return proto.CompactTextString(m) }
func (*Denoms) ProtoMessage()    {}
func (*Denoms) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad06c3dae272cef8, []int{0}
}
func (m *Denoms) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Denoms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Denoms.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Denoms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Denoms.Merge(m, src)
}
func (m *Denoms) XXX_Size() int {
	return m.Size()
}
func (m *Denoms) XXX_DiscardUnknown() {
	xxx_messageInfo_Denoms.DiscardUnknown(m)
}

var xxx_messageInfo_Denoms proto.InternalMessageInfo

func (m *Denoms) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Denoms) GetAllowance() types.Coin {
	if m != nil {
		return m.Allowance
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Denoms)(nil), "noble.cctp.Denoms")
}

func init() { proto.RegisterFile("cctp/denoms.proto", fileDescriptor_ad06c3dae272cef8) }

var fileDescriptor_ad06c3dae272cef8 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x84, 0x8a, 0x6a, 0x26, 0x22, 0x86, 0xd0, 0xc1, 0x54, 0x4c, 0x5d, 0xf0, 0xa9,
	0x65, 0x66, 0x29, 0x8c, 0x4c, 0x1d, 0xd9, 0x6c, 0xe7, 0x14, 0x22, 0x25, 0xbe, 0x28, 0xe7, 0x06,
	0x78, 0x0b, 0x1e, 0xab, 0x63, 0x47, 0x26, 0x84, 0x92, 0x17, 0x41, 0x71, 0x40, 0x6c, 0x77, 0xf7,
	0xdf, 0x7d, 0xba, 0x4f, 0x5e, 0x38, 0x17, 0x1a, 0xc8, 0xd1, 0x53, 0xcd, 0xba, 0x69, 0x29, 0x50,
	0x2a, 0x3d, 0xd9, 0x0a, 0xf5, 0x18, 0x2c, 0x2e, 0x0b, 0x2a, 0x28, 0x8e, 0x61, 0xac, 0xa6, 0x8d,
	0x85, 0x72, 0xc4, 0x35, 0x31, 0x58, 0xc3, 0x08, 0xdd, 0xda, 0x62, 0x30, 0x6b, 0x70, 0x54, 0xfa,
	0x29, 0xbf, 0x31, 0x72, 0xf6, 0x18, 0x89, 0x69, 0x26, 0xcf, 0x4c, 0x9e, 0xb7, 0xc8, 0x9c, 0x89,
	0xa5, 0x58, 0xcd, 0x77, 0x7f, 0x6d, 0x7a, 0x2f, 0xe7, 0xa6, 0xaa, 0xe8, 0xd5, 0x78, 0x87, 0xd9,
	0xc9, 0x52, 0xac, 0xce, 0x37, 0x57, 0x7a, 0xe2, 0xea, 0x91, 0xab, 0x7f, 0xb9, 0xfa, 0x81, 0x4a,
	0xbf, 0x3d, 0x3d, 0x7c, 0x5d, 0x27, 0xbb, 0xff, 0x8b, 0xed, 0xd3, 0xa1, 0x57, 0xe2, 0xd8, 0x2b,
	0xf1, 0xdd, 0x2b, 0xf1, 0x31, 0xa8, 0xe4, 0x38, 0xa8, 0xe4, 0x73, 0x50, 0xc9, 0xf3, 0xa6, 0x28,
	0xc3, 0xcb, 0xde, 0x6a, 0x47, 0x35, 0x70, 0x68, 0x8d, 0x2f, 0xb0, 0xa2, 0x0e, 0x6f, 0x3b, 0xf4,
	0x61, 0xdf, 0x22, 0x43, 0xd4, 0x83, 0x37, 0x88, 0xe6, 0xe1, 0xbd, 0x41, 0xb6, 0xb3, 0xf8, 0xf7,
	0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0x20, 0x45, 0xbc, 0x0e, 0x01, 0x00, 0x00,
}

func (m *Denoms) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Denoms) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Denoms) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Allowance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDenoms(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintDenoms(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDenoms(dAtA []byte, offset int, v uint64) int {
	offset -= sovDenoms(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Denoms) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovDenoms(uint64(l))
	}
	l = m.Allowance.Size()
	n += 1 + l + sovDenoms(uint64(l))
	return n
}

func sovDenoms(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDenoms(x uint64) (n int) {
	return sovDenoms(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Denoms) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDenoms
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Denoms: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Denoms: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenoms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDenoms
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDenoms
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allowance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenoms
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDenoms
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDenoms
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Allowance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDenoms(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDenoms
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDenoms(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDenoms
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDenoms
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDenoms
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDenoms
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDenoms
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDenoms
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDenoms        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDenoms          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDenoms = fmt.Errorf("proto: unexpected end of group")
)
